// Categorized OSM tags for filtering elements
export const tagGroups = {
  Entertainment: [
    'amenity:casino',
    'amenity:planetarium',
    'leisure:stadium',
    'leisure:water_park',
    'tourism:aquarium',
    'tourism:theme_park',
    'tourism:zoo',
    'building:stadium',
    'aeroway:spaceport',
    'amenity:brothel',
    'amenity:cinema',
    'amenity:gambling',
    'amenity:love_hotel',
    'amenity:music_venue',
    'amenity:nightclub',
    'amenity:public_bookcase',
    'amenity:stage',
    'amenity:stripclub',
    'amenity:swingerclub',
  ],
  Drinking: [
    'amenity:bar',
    'amenity:biergarten',
    'amenity:cafe',
    'amenity:pub',
    'craft:winery',
  ],
  Financial: [
    'amenity:atm',
    'amenity:payment_terminal',
    'amenity:bank',
    'amenity:bureau_de_change',
    'amenity:money_transfer',
    'amenity:payment_centre',
  ],
  Cars: [
    'amenity:weighbridge',
    'amenity:taxi',
    //'amenity:parking',
    'highway:hitchhiking',
    'amenity:car_rental',
    'amenity:car_sharing',
    'amenity:car_wash',
    'amenity:compressed_air',
    'amenity:vehicle_inspection',
    'amenity:charging_station',
    'amenity:fuel',
  ],
  Bus: [
    'amenity:bus_station',
  ],
  Bikes: [
    'amenity:bicycle_parking',
    'amenity:bicycle_repair_station',
    'amenity:bicycle_rental',
    'amenity:bicycle_wash',
    'amenity:motorcycle_parking',
  ],
  Water_Transport: [
    'amenity:ferry_terminal',
    'amenity:boat_rental',
    'amenity:boat_sharing',
    'man_made:pier',
    'office:harbour_master',
    'leisure:marina',
  ],
  Air_Transport: [
    'aerialway:cable_car',
    'aerialway:gondola',
    'aerialway:mixed_lift',
    'aerialway:chair_lift',
    'aerialway:goods',
    'aerialway:station',
    'aeroway:aerodrome',
    'aeroway:helipad',
    'aeroway:heliport',
    'aeroway:runway',
    'aeroway:terminal',
  ],
  Rail: [
    'railway:funicular',
    'building:train_station',
  ],
  Traffic: [
    'boundary:limited_traffic_zone',
    'boundary:low_emission_zone',
    'barrier:border_control',
  ],
  Education: [
    'amenity:community_centre',
    'amenity:events_venue',
    'amenity:driver_training',
    'amenity:college',
    'amenity:dancing_school',
    'amenity:driving_school',
    'amenity:kindergarten',
    'amenity:language_school',
    'amenity:library',
    'amenity:reseach_institute',
    'amenity:training',
    'amenity:music_school',
    'amenity:school',
    'amenity:traffic_park',
    'amenity:university',
    'amenity:conference_centre',
  ],
  Sport: [
    'leisure:ice_rink',
    'leisure:miniature_golf',
    'amenity:public_bath',
    'amenity:surf_school',
    'amenity:dive_centre',
    'landuse:winter_sports',
    
    
  ],
  Culture: [
    'amenity:theatre',
    'amenity:exhibition_centre',
    'amenity:arts_centre',
    'amenity:monastery',
    'amenity:place_of_worship',
    'building:cathedral',
    'building:church',
    'building:kingdom_hall',
    'building:monastery',
    'building:mosque',
    'building:synagogue',
    'building:temple',
    'building:museum',
    'tourism:artwork',
    'tourism:gallery',
    'tourism:museum',
  ],
  Nature: [
    'landuse:salt_pond',
    'mountain_pass:yes',
    'boundary:aboriginal_lands',
    'boundary:national_park',
    'boundary:protected_area',
    'geological:volcanic_caldera_rim',
    'geological:volcanic_lava_field',
    'geological:volcanic_vent',
    'geological:columnar_jointing',
    'geological:hoodoo',
    'geological:dyke',
    'geological:tor',
    'geological:inselberg',
    'leisure:bird_hide',
    //'leisure:garden',
    'leisure:nature_reserve',
    'natural:beach',
    'natural:blowhole',
    'natural:geyser',
    'natural:glacier',
    'natural:hot_spring',
    'natural:isthmus',
    'natural:arch',
    'natural:cave_entrance',
    //'natural:cliff',
    'natural:dune',
    'natural:fumarole',
    'natural:volcano',
    'tourism:viewpoint',
    'waterway:waterfall',
  ],
  Eating: [
    'amenity:fast_food',
    'amenity:ice_cream',
    'amenity:marketplace',
    'amenity:restaurant',
    'amenity:food_court',
    'shop:ice_cream',
    'landuse:vineyard',
    
    'shop:mall',
  ],
  History: [
    'historic:aircraft',
    'historic:aqueduct',
    'historic:archaeological_site',
    'historic:building',
    'historic:castle',
    'historic:castle_wall',
    'historic:church',
    'historic:city_gate',
    'historic:citywalls',
    'historic:district',
    'historic:farm',
    'historic:fort',
    'historic:house',
    'historic:locomotive',
    'historic:manor',
    'historic:monastery',
    'historic:mine',
    'historic:monument',
    'historic:mosque',
    'historic:road',
    'historic:ruins',
    'historic:ship',
    'historic:temple',
    'historic:tomb',
    'historic:tower',
    'historic:wreck',
    'building:bridge',
    'building:beach_hut',
    'building:castle',
    'building:ship',
    'building:triumphal_arch',
    'barrier:city_wall',
    'man_made:lighthouse',
    'man_made:observatory',
    'man_made:watermill',
    'man_made:windmill',
  ],
  Tourism: [
    'leisure:beach_resort',
    'amenity:ranger_station',
    'office:guide',
    'tourism:alpine_hut',
    'tourism:attraction',
    'tourism:yes',
  ],
  Health: [
    'amenity:kneipp_water_cure',
    'amenity:clinic',
    'amenity:dentist',
    'amenity:doctors',
    'amenity:hospital',
    'amenity:pharmacy',
    'amenity:veterinary',
  ],
  Other: [
    'boundary:hazard',
    'boundary:timezone',
  ],
};

// Flattened set of all allowed tags for backward compatibility
// Only include specific categories: Entertainment, Culture, Nature, History, Tourism
const allowedCategories = ['Entertainment', 'Culture', 'Nature', 'History', 'Tourism'];
export const allowedTags = new Set([
  ...allowedCategories.flatMap(category => tagGroups[category as keyof typeof tagGroups] || [])
]);

// Function to get the group for a given tag
export const getTagGroup = (tag: string): string | null => {
  for (const [groupName, tags] of Object.entries(tagGroups)) {
    if (tags.includes(tag)) {
      return groupName;
    }
  }
  return null;
};

// Function to get display name for a tag
export const getTagDisplayName = (tag: string): string => {
  const [key, value] = tag.split(':');
  if (value) {
    return `${key}: ${value.replace(/_/g, ' ')}`;
  }
  return key.replace(/_/g, ' ');
};
